//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuTube.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuTube.Helpers.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar!.
        /// </summary>
        public static string Boton_Buscar {
            get {
                return ResourceManager.GetString("Boton_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Boton_Cerrar {
            get {
                return ResourceManager.GetString("Boton_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Descargar Mp3.
        /// </summary>
        public static string Boton_DescargarMp3 {
            get {
                return ResourceManager.GetString("Boton_DescargarMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Buscar Mp3.
        /// </summary>
        public static string BuscarMp3 {
            get {
                return ResourceManager.GetString("BuscarMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes descargar en formato MP3 toda una selección de temas utilizando el buscador, con el criterio de busqueda que creas conveniente (artista, cancion, album, etc)..
        /// </summary>
        public static string BuscarMp3Help {
            get {
                return ResourceManager.GetString("BuscarMp3Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Buscar Mp4.
        /// </summary>
        public static string BuscarMp4 {
            get {
                return ResourceManager.GetString("BuscarMp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes descargar en formato MP4 toda una selección de videos utilizando el buscador, con el criterio de busqueda que creas conveniente (artista, cancion, album, etc)..
        /// </summary>
        public static string BuscarMp4Help {
            get {
                return ResourceManager.GetString("BuscarMp4Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Descargar Link.
        /// </summary>
        public static string DescargarLink {
            get {
                return ResourceManager.GetString("DescargarLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tienes un video en youtube que quieres en formato mp3, puedes ingresarlo y descargarlo directamente sin intermediarios, solo copia el link y pegalo en la barra de descargas..
        /// </summary>
        public static string DescargarLinkHelp {
            get {
                return ResourceManager.GetString("DescargarLinkHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando....
        /// </summary>
        public static string Dialogo_Procesando_Titulo {
            get {
                return ResourceManager.GetString("Dialogo_Procesando_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando....
        /// </summary>
        public static string Dialogo_VistaPrevia_Titulo {
            get {
                return ResourceManager.GetString("Dialogo_VistaPrevia_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el Criterio de Búsqueda.
        /// </summary>
        public static string Error_BusquedaEnBlanco {
            get {
                return ResourceManager.GetString("Error_BusquedaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la Url de un video.
        /// </summary>
        public static string Error_UrlEnBlanco {
            get {
                return ResourceManager.GetString("Error_UrlEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una Url de youtube válida.
        /// </summary>
        public static string Error_UrlInvalida {
            get {
                return ResourceManager.GetString("Error_UrlInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for....
        /// </summary>
        public static string Textbox_Principal {
            get {
                return ResourceManager.GetString("Textbox_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motube.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
    }
}
